.TH "Mouse" 3 "Version 1.0" "MyGameEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mouse \- Namespace containing mouse button code definitions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBButton\fP { \fBButton1\fP = 0, \fBButton2\fP = 1, \fBButton3\fP = 2, \fBButton4\fP = 3, \fBButton5\fP = 4, \fBButton6\fP = 5, \fBButton7\fP = 6, \fBButton8\fP = 7, \fBLeft\fP = Button1, \fBRight\fP = Button2, \fBMiddle\fP = Button3 }"
.br
.RI "Enumeration of mouse button codes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Namespace containing mouse button code definitions\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMouse::Button\fP"

.PP
Enumeration of mouse button codes\&. Defines button codes for standard mouse buttons\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Input/Input\&.h\fP\&.
.PP
Definition at line \fB110\fP of file \fBInput\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MyGameEngine from the source code\&.
