.TH "SceneData" 3 "Version 1.0" "MyGameEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneData \- Structure holding per-scene rendering data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Renderer\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMatrix4\fP \fBviewProjectionMatrix\fP"
.br
.RI "The combined view and projection matrix for the current scene\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure holding per-scene rendering data\&. 

Contains the view-projection matrix used for transforming world coordinates to clip space during rendering\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Renderer\&.h\fP\&.
.PP
Definition at line \fB15\fP of file \fBRenderer\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMatrix4\fP SceneData::viewProjectionMatrix"

.PP
The combined view and projection matrix for the current scene\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Renderer\&.h\fP\&.
.PP
Definition at line \fB20\fP of file \fBRenderer\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MyGameEngine from the source code\&.
