.TH "Shader" 3 "Version 1.0" "MyGameEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shader \- Represents an OpenGL shader program composed of vertex and fragment shaders\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Shader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShader\fP (const std::string &vertexSrc, const std::string &fragmentSrc)"
.br
.RI "Constructs a \fBShader\fP from vertex and fragment source code strings\&. "
.ti -1c
.RI "\fB~Shader\fP ()"
.br
.RI "Destructor that cleans up the OpenGL shader program\&. "
.ti -1c
.RI "void \fBBind\fP () const"
.br
.RI "Binds the shader program for use in rendering\&. "
.ti -1c
.RI "void \fBUnbind\fP () const"
.br
.RI "Unbinds the shader program\&. "
.ti -1c
.RI "void \fBSetInt\fP (const std::string &name, \fBi32\fP value)"
.br
.RI "Sets an integer uniform variable in the shader\&. "
.ti -1c
.RI "void \fBSetFloat\fP (const std::string &name, \fBf32\fP value)"
.br
.RI "Sets a float uniform variable in the shader\&. "
.ti -1c
.RI "void \fBSetVector2\fP (const std::string &name, const \fBVector2\fP &value)"
.br
.RI "Sets a \fBVector2\fP uniform variable in the shader\&. "
.ti -1c
.RI "void \fBSetVector3\fP (const std::string &name, const \fBVector3\fP &value)"
.br
.RI "Sets a \fBVector3\fP uniform variable in the shader\&. "
.ti -1c
.RI "void \fBSetVector4\fP (const std::string &name, const \fBVector4\fP &value)"
.br
.RI "Sets a \fBVector4\fP uniform variable in the shader\&. "
.ti -1c
.RI "void \fBSetMatrix3\fP (const std::string &name, const \fBMatrix3\fP &value)"
.br
.RI "Sets a \fBMatrix3\fP uniform variable in the shader\&. "
.ti -1c
.RI "void \fBSetMatrix4\fP (const std::string &name, const \fBMatrix4\fP &value)"
.br
.RI "Sets a \fBMatrix4\fP uniform variable in the shader\&. "
.ti -1c
.RI "\fBu32\fP \fBGetRendererID\fP () const"
.br
.RI "Gets the OpenGL renderer ID of the shader program\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRef\fP< \fBShader\fP > \fBCreate\fP (const std::string &vertexSrc, const std::string &fragmentSrc)"
.br
.RI "Creates a \fBShader\fP from vertex and fragment source code strings\&. "
.ti -1c
.RI "static \fBRef\fP< \fBShader\fP > \fBCreateFromFiles\fP (const std::string &vertexPath, const std::string &fragmentPath)"
.br
.RI "Creates a \fBShader\fP by loading vertex and fragment shader source code from files\&. "
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBCompileShader\fP (GLenum type, const std::string &source)"
.br
.RI "Compiles a shader of the given type from source code\&. "
.ti -1c
.RI "\fBi32\fP \fBGetUniformLocation\fP (const std::string &name)"
.br
.RI "Retrieves the location of a uniform variable, using caching for performance\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBm_RendererID\fP"
.br
.RI "The OpenGL renderer ID for the shader program\&. "
.ti -1c
.RI "std::unordered_map< std::string, \fBi32\fP > \fBm_UniformLocationCache\fP"
.br
.RI "Cache mapping uniform variable names to their OpenGL locations\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents an OpenGL shader program composed of vertex and fragment shaders\&. 

This class encapsulates the creation, compilation, linking, and management of OpenGL shader programs\&. It provides methods to bind/unbind the shader and set uniform variables of various types (int, float, vectors, matrices)\&.

.PP
\fBKey\fP features:
.IP "\(bu" 2
Load shaders from source code strings or files
.IP "\(bu" 2
Compile and link shader programs
.IP "\(bu" 2
Set uniform variables with caching for performance
.PP

.PP
\fBNote\fP
.RS 4
Requires a valid OpenGL context to function properly\&. 

.PP
All OpenGL calls are made through this class; direct OpenGL calls should be avoided\&. 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/ResourceManager\&.h\fP, and \fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB40\fP of file \fBShader\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Shader::Shader (const std::string & vertexSrc, const std::string & fragmentSrc)"

.PP
Constructs a \fBShader\fP from vertex and fragment source code strings\&. Compiles the provided vertex and fragment shader source code, links them into a shader program, and prepares it for use\&.

.PP
\fBParameters\fP
.RS 4
\fIvertexSrc\fP The source code for the vertex shader 
.br
\fIfragmentSrc\fP The source code for the fragment shader 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB5\fP of file \fBShader\&.cpp\fP\&.
.PP
References \fBCompileShader()\fP, and \fBm_RendererID\fP\&.
.SS "Shader::~Shader ()"

.PP
Destructor that cleans up the OpenGL shader program\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB29\fP of file \fBShader\&.cpp\fP\&.
.PP
References \fBm_RendererID\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Shader::Bind () const"

.PP
Binds the shader program for use in rendering\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB53\fP of file \fBShader\&.cpp\fP\&.
.PP
References \fBm_RendererID\fP\&.
.SS "\fBu32\fP Shader::CompileShader (GLenum type, const std::string & source)\fR [private]\fP"

.PP
Compiles a shader of the given type from source code\&. 
.PP
\fBParameters\fP
.RS 4
\fItype\fP The type of shader (GL_VERTEX_SHADER or GL_FRAGMENT_SHADER) 
.br
\fIsource\fP The source code of the shader 
.RE
.PP
\fBReturns\fP
.RS 4
\fBu32\fP The OpenGL ID of the compiled shader 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB34\fP of file \fBShader\&.cpp\fP\&.
.PP
Referenced by \fBShader()\fP\&.
.SS "\fBRef\fP< \fBShader\fP > Shader::Create (const std::string & vertexSrc, const std::string & fragmentSrc)\fR [static]\fP, \fR [nodiscard]\fP"

.PP
Creates a \fBShader\fP from vertex and fragment source code strings\&. 
.PP
\fBParameters\fP
.RS 4
\fIvertexSrc\fP The source code for the vertex shader 
.br
\fIfragmentSrc\fP The source code for the fragment shader 
.RE
.PP
\fBReturns\fP
.RS 4
\fBRef<Shader>\fP A reference-counted pointer to the created \fBShader\fP 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB124\fP of file \fBShader\&.cpp\fP\&.
.PP
Referenced by \fBCreateFromFiles()\fP, and \fBResourceManager::LoadShaderFromSource()\fP\&.
.SS "\fBRef\fP< \fBShader\fP > Shader::CreateFromFiles (const std::string & vertexPath, const std::string & fragmentPath)\fR [static]\fP, \fR [nodiscard]\fP"

.PP
Creates a \fBShader\fP by loading vertex and fragment shader source code from files\&. 
.PP
\fBParameters\fP
.RS 4
\fIvertexPath\fP The file path to the vertex shader source code 
.br
\fIfragmentPath\fP The file path to the fragment shader source code 
.RE
.PP
\fBReturns\fP
.RS 4
\fBRef<Shader>\fP A reference-counted pointer to the created \fBShader\fP 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB128\fP of file \fBShader\&.cpp\fP\&.
.PP
References \fBCreate()\fP\&.
.PP
Referenced by \fBResourceManager::LoadShader()\fP\&.
.SS "\fBu32\fP Shader::GetRendererID () const\fR [inline]\fP, \fR [nodiscard]\fP"

.PP
Gets the OpenGL renderer ID of the shader program\&. 
.PP
\fBReturns\fP
.RS 4
\fBu32\fP The OpenGL renderer ID 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB130\fP of file \fBShader\&.h\fP\&.
.PP
References \fBm_RendererID\fP\&.
.SS "\fBi32\fP Shader::GetUniformLocation (const std::string & name)\fR [private]\fP"

.PP
Retrieves the location of a uniform variable, using caching for performance\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the uniform variable 
.RE
.PP
\fBReturns\fP
.RS 4
\fBi32\fP The location of the uniform variable 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB61\fP of file \fBShader\&.cpp\fP\&.
.PP
References \fBm_RendererID\fP, and \fBm_UniformLocationCache\fP\&.
.PP
Referenced by \fBSetFloat()\fP, \fBSetInt()\fP, \fBSetMatrix3()\fP, \fBSetMatrix4()\fP, \fBSetVector2()\fP, \fBSetVector3()\fP, and \fBSetVector4()\fP\&.
.SS "void Shader::SetFloat (const std::string & name, \fBf32\fP value)"

.PP
Sets a float uniform variable in the shader\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the uniform variable 
.br
\fIvalue\fP The float value to set 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB82\fP of file \fBShader\&.cpp\fP\&.
.PP
References \fBGetUniformLocation()\fP\&.
.SS "void Shader::SetInt (const std::string & name, \fBi32\fP value)"

.PP
Sets an integer uniform variable in the shader\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the uniform variable 
.br
\fIvalue\fP The integer value to set 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB75\fP of file \fBShader\&.cpp\fP\&.
.PP
References \fBGetUniformLocation()\fP\&.
.SS "void Shader::SetMatrix3 (const std::string & name, const \fBMatrix3\fP & value)"

.PP
Sets a \fBMatrix3\fP uniform variable in the shader\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the uniform variable 
.br
\fIvalue\fP The \fBMatrix3\fP value to set 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB110\fP of file \fBShader\&.cpp\fP\&.
.PP
References \fBGetUniformLocation()\fP\&.
.SS "void Shader::SetMatrix4 (const std::string & name, const \fBMatrix4\fP & value)"

.PP
Sets a \fBMatrix4\fP uniform variable in the shader\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the uniform variable 
.br
\fIvalue\fP The \fBMatrix4\fP value to set 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB117\fP of file \fBShader\&.cpp\fP\&.
.PP
References \fBGetUniformLocation()\fP\&.
.SS "void Shader::SetVector2 (const std::string & name, const \fBVector2\fP & value)"

.PP
Sets a \fBVector2\fP uniform variable in the shader\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the uniform variable 
.br
\fIvalue\fP The \fBVector2\fP value to set 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB89\fP of file \fBShader\&.cpp\fP\&.
.PP
References \fBGetUniformLocation()\fP, \fBVector2::x\fP, and \fBVector2::y\fP\&.
.SS "void Shader::SetVector3 (const std::string & name, const \fBVector3\fP & value)"

.PP
Sets a \fBVector3\fP uniform variable in the shader\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the uniform variable 
.br
\fIvalue\fP The \fBVector3\fP value to set 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB96\fP of file \fBShader\&.cpp\fP\&.
.PP
References \fBGetUniformLocation()\fP\&.
.SS "void Shader::SetVector4 (const std::string & name, const \fBVector4\fP & value)"

.PP
Sets a \fBVector4\fP uniform variable in the shader\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the uniform variable 
.br
\fIvalue\fP The \fBVector4\fP value to set 
.RE
.PP

.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB103\fP of file \fBShader\&.cpp\fP\&.
.PP
References \fBGetUniformLocation()\fP\&.
.SS "void Shader::Unbind () const"

.PP
Unbinds the shader program\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB57\fP of file \fBShader\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBu32\fP Shader::m_RendererID\fR [private]\fP"

.PP
The OpenGL renderer ID for the shader program\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB172\fP of file \fBShader\&.h\fP\&.
.PP
Referenced by \fBBind()\fP, \fBGetRendererID()\fP, \fBGetUniformLocation()\fP, \fBShader()\fP, and \fB~Shader()\fP\&.
.SS "std::unordered_map<std::string, \fBi32\fP> Shader::m_UniformLocationCache\fR [private]\fP"

.PP
Cache mapping uniform variable names to their OpenGL locations\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Shader\&.h\fP\&.
.PP
Definition at line \fB178\fP of file \fBShader\&.h\fP\&.
.PP
Referenced by \fBGetUniformLocation()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MyGameEngine from the source code\&.
