.TH "Window::WindowData" 3 "Version 1.0" "MyGameEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Window::WindowData \- Internal data structure for window properties and state\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBTitle\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBWidth\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBHeight\fP"
.br
.ti -1c
.RI "\fBEventCallbackFn\fP \fBEventCallback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal data structure for window properties and state\&. 
.PP
\fBExamples\fP
.in +1c
\fBC:/Users/PC/source/repos/engine/src/Graphics/Window\&.h\fP\&.
.PP
Definition at line \fB297\fP of file \fBWindow\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEventCallbackFn\fP Window::WindowData::EventCallback"

.PP
Definition at line \fB300\fP of file \fBWindow\&.h\fP\&.
.SS "\fBu32\fP Window::WindowData::Height"

.PP
Definition at line \fB299\fP of file \fBWindow\&.h\fP\&.
.SS "std::string Window::WindowData::Title"

.PP
Definition at line \fB298\fP of file \fBWindow\&.h\fP\&.
.SS "\fBu32\fP Window::WindowData::Width"

.PP
Definition at line \fB299\fP of file \fBWindow\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MyGameEngine from the source code\&.
