var annotated_dup =
[
    [ "Log", "namespace_log.html", [
      [ "Logger", "class_log_1_1_logger.html", null ]
    ] ],
    [ "Time", "namespace_time.html", [
      [ "Timer", "class_time_1_1_timer.html", "class_time_1_1_timer" ]
    ] ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "Engine", "class_engine.html", "class_engine" ],
    [ "Event", "class_event.html", "class_event" ],
    [ "EventDispatcher", "class_event_dispatcher.html", "class_event_dispatcher" ],
    [ "GLErrorChecker", "class_g_l_error_checker.html", "class_g_l_error_checker" ],
    [ "GraphicsContext", "class_graphics_context.html", "class_graphics_context" ],
    [ "IndexBuffer", "class_index_buffer.html", "class_index_buffer" ],
    [ "Input", "class_input.html", "class_input" ],
    [ "Material", "class_material.html", "class_material" ],
    [ "MaterialProperties", "struct_material_properties.html", null ],
    [ "Matrix3", "struct_matrix3.html", null ],
    [ "Matrix4", "struct_matrix4.html", null ],
    [ "Mesh", "class_mesh.html", "class_mesh" ],
    [ "ModelLoader", "class_model_loader.html", "class_model_loader" ],
    [ "Plane", "struct_plane.html", null ],
    [ "Quaternion", "struct_quaternion.html", null ],
    [ "Ray", "struct_ray.html", null ],
    [ "RenderCommand", "class_render_command.html", null ],
    [ "Renderer", "class_renderer.html", "class_renderer" ],
    [ "ResourceManager", "class_resource_manager.html", "class_resource_manager" ],
    [ "Scene", "class_scene.html", "class_scene" ],
    [ "SceneData", "struct_scene_data.html", "struct_scene_data" ],
    [ "SceneObject", "struct_scene_object.html", "struct_scene_object" ],
    [ "Shader", "class_shader.html", "class_shader" ],
    [ "TestApp", "class_test_app.html", "class_test_app" ],
    [ "TestScene", "class_test_scene.html", "class_test_scene" ],
    [ "Texture", "class_texture.html", "class_texture" ],
    [ "Transform", "class_transform.html", null ],
    [ "Vector2", "struct_vector2.html", "struct_vector2" ],
    [ "Vector3", "struct_vector3.html", null ],
    [ "Vector4", "struct_vector4.html", null ],
    [ "Vertex", "struct_vertex.html", "struct_vertex" ],
    [ "VertexArray", "class_vertex_array.html", "class_vertex_array" ],
    [ "VertexBuffer", "class_vertex_buffer.html", "class_vertex_buffer" ],
    [ "VertexBufferElement", "struct_vertex_buffer_element.html", "struct_vertex_buffer_element" ],
    [ "VertexBufferLayout", "class_vertex_buffer_layout.html", "class_vertex_buffer_layout" ],
    [ "Window", "class_window.html", "class_window" ],
    [ "WindowCloseEvent", "class_window_close_event.html", "class_window_close_event" ],
    [ "WindowProps", "struct_window_props.html", "struct_window_props" ],
    [ "WindowResizeEvent", "class_window_resize_event.html", "class_window_resize_event" ]
];