MyGameEngine: GLErrorChecker Class Reference
GLErrorChecker Class Reference
Utility class for checking and logging OpenGL errors.
#include <GLError.h>
Public Member Functions
GLErrorChecker (const char *context)
Constructs a GLErrorChecker with a context description.
~GLErrorChecker ()
Destructor that checks for OpenGL errors.
void CheckErrors () const
Checks for OpenGL errors and logs them.
Static Public Member Functions
static const char * GetErrorString (GLenum error)
Converts an OpenGL error code to a human-readable string.
Private Attributes
const char * m_Context
Context description for error logging.
Detailed Description
Utility class for checking and logging OpenGL errors.
This class provides functionality to check for OpenGL errors after OpenGL function calls. It logs any detected errors using the engine's logging system. The class can be used in a RAII manner to automatically check for errors when going out of scope.
Usage:
{
  GLErrorChecker glError("Rendering Frame");
 // OpenGL calls...
} // Errors checked automatically here
Note
This class is intended for debugging purposes and may be disabled in release builds for performance.
Definition at line 26 of file GLError.h.
Constructor & Destructor Documentation
GLErrorChecker()
GLErrorChecker::GLErrorChecker (const char * context) inline
Constructs a GLErrorChecker with a context description.
Definition at line 29 of file GLError.h.
References m_Context.
~GLErrorChecker()
GLErrorChecker::~GLErrorChecker () inline
Destructor that checks for OpenGL errors.
Definition at line 35 of file GLError.h.
References CheckErrors().
Member Function Documentation
CheckErrors()
void GLErrorChecker::CheckErrors () const inline
Checks for OpenGL errors and logs them.
Definition at line 40 of file GLError.h.
References GetErrorString(), and m_Context.
Referenced by ~GLErrorChecker().
GetErrorString()
const char * GLErrorChecker::GetErrorString (GLenum error) inline static
Converts an OpenGL error code to a human-readable string.
Definition at line 58 of file GLError.h.
Referenced by CheckErrors().
Member Data Documentation
m_Context
const char* GLErrorChecker::m_Context private
Context description for error logging.
Definition at line 72 of file GLError.h.
Referenced by CheckErrors(), and GLErrorChecker().
The documentation for this class was generated from the following file:
src/Graphics/GLError.h