MyGameEngine: Shader Class Reference
Shader Class Reference
Represents an OpenGL shader program composed of vertex and fragment shaders.
#include <Shader.h>
Public Member Functions
Shader (const std::string &vertexSrc, const std::string &fragmentSrc)
Constructs a Shader from vertex and fragment source code strings.
~Shader ()
Destructor that cleans up the OpenGL shader program.
void Bind () const
Binds the shader program for use in rendering.
void Unbind () const
Unbinds the shader program.
void SetInt (const std::string &name, i32 value)
Sets an integer uniform variable in the shader.
void SetFloat (const std::string &name, f32 value)
Sets a float uniform variable in the shader.
void SetVector2 (const std::string &name, const Vector2 &value)
Sets a Vector2 uniform variable in the shader.
void SetVector3 (const std::string &name, const Vector3 &value)
Sets a Vector3 uniform variable in the shader.
void SetVector4 (const std::string &name, const Vector4 &value)
Sets a Vector4 uniform variable in the shader.
void SetMatrix3 (const std::string &name, const Matrix3 &value)
Sets a Matrix3 uniform variable in the shader.
void SetMatrix4 (const std::string &name, const Matrix4 &value)
Sets a Matrix4 uniform variable in the shader.
u32 GetRendererID () const
Gets the OpenGL renderer ID of the shader program.
Static Public Member Functions
static Ref< Shader > Create (const std::string &vertexSrc, const std::string &fragmentSrc)
Creates a Shader from vertex and fragment source code strings.
static Ref< Shader > CreateFromFiles (const std::string &vertexPath, const std::string &fragmentPath)
Creates a Shader by loading vertex and fragment shader source code from files.
Private Member Functions
u32 CompileShader (GLenum type, const std::string &source)
Compiles a shader of the given type from source code.
i32 GetUniformLocation (const std::string &name)
Retrieves the location of a uniform variable, using caching for performance.
Private Attributes
u32 m_RendererID
The OpenGL renderer ID for the shader program.
std::unordered_map< std::string, i32 > m_UniformLocationCache
Cache mapping uniform variable names to their OpenGL locations.
Detailed Description
Represents an OpenGL shader program composed of vertex and fragment shaders.
This class encapsulates the creation, compilation, linking, and management of OpenGL shader programs. It provides methods to bind/unbind the shader and set uniform variables of various types (int, float, vectors, matrices).
Key features:
Load shaders from source code strings or files
Compile and link shader programs
Set uniform variables with caching for performance
Note
Requires a valid OpenGL context to function properly.
All OpenGL calls are made through this class; direct OpenGL calls should be avoided.
Examples
C:/Users/PC/source/repos/engine/src/Graphics/ResourceManager.h, and C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 40 of file Shader.h.
Constructor & Destructor Documentation
Shader()
Shader::Shader (const std::string & vertexSrc, const std::string & fragmentSrc)
Constructs a Shader from vertex and fragment source code strings.
Compiles the provided vertex and fragment shader source code, links them into a shader program, and prepares it for use.
Parameters
vertexSrc The source code for the vertex shader
fragmentSrc The source code for the fragment shader
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 5 of file Shader.cpp.
References CompileShader(), and m_RendererID.
~Shader()
Shader::~Shader ()
Destructor that cleans up the OpenGL shader program.
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 29 of file Shader.cpp.
References m_RendererID.
Member Function Documentation
Bind()
void Shader::Bind () const
Binds the shader program for use in rendering.
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 53 of file Shader.cpp.
References m_RendererID.
CompileShader()
u32 Shader::CompileShader (GLenum type, const std::string & source) private
Compiles a shader of the given type from source code.
Parameters
type The type of shader (GL_VERTEX_SHADER or GL_FRAGMENT_SHADER)
source The source code of the shader
Returns
u32 The OpenGL ID of the compiled shader
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 34 of file Shader.cpp.
Referenced by Shader().
Create()
Ref< Shader > Shader::Create (const std::string & vertexSrc, const std::string & fragmentSrc) static nodiscard
Creates a Shader from vertex and fragment source code strings.
Parameters
vertexSrc The source code for the vertex shader
fragmentSrc The source code for the fragment shader
Returns
Ref<Shader> A reference-counted pointer to the created Shader
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 124 of file Shader.cpp.
Referenced by CreateFromFiles(), and ResourceManager::LoadShaderFromSource().
CreateFromFiles()
Ref< Shader > Shader::CreateFromFiles (const std::string & vertexPath, const std::string & fragmentPath) static nodiscard
Creates a Shader by loading vertex and fragment shader source code from files.
Parameters
vertexPath The file path to the vertex shader source code
fragmentPath The file path to the fragment shader source code
Returns
Ref<Shader> A reference-counted pointer to the created Shader
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 128 of file Shader.cpp.
References Create().
Referenced by ResourceManager::LoadShader().
GetRendererID()
u32 Shader::GetRendererID () const inline nodiscard
Gets the OpenGL renderer ID of the shader program.
Returns
u32 The OpenGL renderer ID
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 130 of file Shader.h.
References m_RendererID.
GetUniformLocation()
i32 Shader::GetUniformLocation (const std::string & name) private
Retrieves the location of a uniform variable, using caching for performance.
Parameters
name The name of the uniform variable
Returns
i32 The location of the uniform variable
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 61 of file Shader.cpp.
References m_RendererID, and m_UniformLocationCache.
Referenced by SetFloat(), SetInt(), SetMatrix3(), SetMatrix4(), SetVector2(), SetVector3(), and SetVector4().
SetFloat()
void Shader::SetFloat (const std::string & name, f32 value)
Sets a float uniform variable in the shader.
Parameters
name The name of the uniform variable
value The float value to set
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 82 of file Shader.cpp.
References GetUniformLocation().
SetInt()
void Shader::SetInt (const std::string & name, i32 value)
Sets an integer uniform variable in the shader.
Parameters
name The name of the uniform variable
value The integer value to set
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 75 of file Shader.cpp.
References GetUniformLocation().
SetMatrix3()
void Shader::SetMatrix3 (const std::string & name, const Matrix3 & value)
Sets a Matrix3 uniform variable in the shader.
Parameters
name The name of the uniform variable
value The Matrix3 value to set
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 110 of file Shader.cpp.
References GetUniformLocation().
SetMatrix4()
void Shader::SetMatrix4 (const std::string & name, const Matrix4 & value)
Sets a Matrix4 uniform variable in the shader.
Parameters
name The name of the uniform variable
value The Matrix4 value to set
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 117 of file Shader.cpp.
References GetUniformLocation().
SetVector2()
void Shader::SetVector2 (const std::string & name, const Vector2 & value)
Sets a Vector2 uniform variable in the shader.
Parameters
name The name of the uniform variable
value The Vector2 value to set
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 89 of file Shader.cpp.
References GetUniformLocation(), Vector2::x, and Vector2::y.
SetVector3()
void Shader::SetVector3 (const std::string & name, const Vector3 & value)
Sets a Vector3 uniform variable in the shader.
Parameters
name The name of the uniform variable
value The Vector3 value to set
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 96 of file Shader.cpp.
References GetUniformLocation().
SetVector4()
void Shader::SetVector4 (const std::string & name, const Vector4 & value)
Sets a Vector4 uniform variable in the shader.
Parameters
name The name of the uniform variable
value The Vector4 value to set
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 103 of file Shader.cpp.
References GetUniformLocation().
Unbind()
void Shader::Unbind () const
Unbinds the shader program.
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 57 of file Shader.cpp.
Member Data Documentation
m_RendererID
u32 Shader::m_RendererID private
The OpenGL renderer ID for the shader program.
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 172 of file Shader.h.
Referenced by Bind(), GetRendererID(), GetUniformLocation(), Shader(), and ~Shader().
m_UniformLocationCache
std::unordered_map<std::string, i32> Shader::m_UniformLocationCache private
Cache mapping uniform variable names to their OpenGL locations.
Examples
C:/Users/PC/source/repos/engine/src/Graphics/Shader.h.
Definition at line 178 of file Shader.h.
Referenced by GetUniformLocation().
The documentation for this class was generated from the following files:
src/Graphics/Shader.h
src/Graphics/Shader.cpp