MyGameEngine: ModelLoader Class Reference
ModelLoader Class Reference
Utility class for loading 3D models and meshes from files.
#include <ModelLoader.h>
Static Public Member Functions
static Ref< Mesh > LoadMesh (const std::string &filepath)
Loads a single mesh from the specified file.
static std::vector< Ref< Mesh > > LoadModel (const std::string &filepath)
Loads an entire model from the specified file.
Static Private Member Functions
static void ProcessNode (aiNode *node, const aiScene *scene, std::vector< Ref< Mesh > > &meshes)
Recursively processes a node in the Assimp scene graph.
static Ref< Mesh > ProcessMesh (aiMesh *mesh)
Processes an individual Assimp mesh and converts it to a Mesh object.
static std::vector< u32 > LoadIndices (aiMesh *mesh)
static std::vector< Vertex > LoadVertices (aiMesh *mesh)
Detailed Description
Utility class for loading 3D models and meshes from files.
This class uses the Assimp library to load 3D model files in various formats (e.g., OBJ, FBX, STL) and converts them into Mesh objects usable by the engine. It handles parsing the model file, extracting vertex and index data, and creating Mesh instances with associated materials.
Key features:
Load single meshes or entire models with multiple meshes
Support for common 3D file formats via Assimp
Automatic processing of vertices, indices, normals, and texture coordinates
Note
Requires Assimp library to be linked with the project.
Currently does not handle animations or skeletal data.
Examples
C:/Users/PC/source/repos/engine/src/Graphics/ModelLoader.h.
Definition at line 33 of file ModelLoader.h.
Member Function Documentation
LoadIndices()
std::vector< u32 > ModelLoader::LoadIndices (aiMesh * mesh) static private
Definition at line 93 of file ModelLoader.cpp.
LoadMesh()
Ref< Mesh > ModelLoader::LoadMesh (const std::string & filepath) static
Loads a single mesh from the specified file.
Uses Assimp to import the model file and extract the first mesh found. Converts the mesh data into a Mesh object.
Parameters
filepath The path to the model file to load
Returns
Ref<Mesh> The loaded mesh object
Note
If the file contains multiple meshes, only the first one is loaded.
Throws an exception if loading fails.
Examples
C:/Users/PC/source/repos/engine/src/Graphics/ModelLoader.h.
Definition at line 5 of file ModelLoader.cpp.
References LoadModel().
LoadModel()
std::vector< Ref< Mesh > > ModelLoader::LoadModel (const std::string & filepath) static
Loads an entire model from the specified file.
Uses Assimp to import the model file and extract all meshes found. Converts each mesh into a Mesh object and returns a list of meshes.
Parameters
filepath The path to the model file to load
Returns
std::vector<Ref<Mesh>> A vector of loaded mesh objects
Note
Supports models with multiple meshes.
Throws an exception if loading fails.
Examples
C:/Users/PC/source/repos/engine/src/Graphics/ModelLoader.h.
Definition at line 10 of file ModelLoader.cpp.
References ProcessNode().
Referenced by LoadMesh().
LoadVertices()
std::vector< Vertex > ModelLoader::LoadVertices (aiMesh * mesh) static private
Definition at line 51 of file ModelLoader.cpp.
ProcessMesh()
Ref< Mesh > ModelLoader::ProcessMesh (aiMesh * mesh) static private
Processes an individual Assimp mesh and converts it to a Mesh object.
Extracts vertex positions, normals, texture coordinates, and indices from the aiMesh structure and creates a Mesh instance.
Parameters
mesh The Assimp mesh to process
Returns
Ref<Mesh> The created Mesh object
Examples
C:/Users/PC/source/repos/engine/src/Graphics/ModelLoader.h.
Definition at line 45 of file ModelLoader.cpp.
Referenced by ProcessNode().
ProcessNode()
void ModelLoader::ProcessNode (aiNode * node, const aiScene * scene, std::vector< Ref< Mesh > > & meshes) static private
Recursively processes a node in the Assimp scene graph.
Traverses the node hierarchy, processing each mesh and its children. Converts meshes into Mesh objects and adds them to the provided list.
Parameters
node The current Assimp node to process
scene The Assimp scene containing the model data
meshes The vector to store processed Mesh objects
Examples
C:/Users/PC/source/repos/engine/src/Graphics/ModelLoader.h.
Definition at line 31 of file ModelLoader.cpp.
References ProcessMesh(), and ProcessNode().
Referenced by LoadModel(), and ProcessNode().
The documentation for this class was generated from the following files:
src/Graphics/ModelLoader.h
src/Graphics/ModelLoader.cpp