MyGameEngine: VertexBufferLayout Class Reference
VertexBufferLayout Class Reference
Defines the layout of vertex attributes in a vertex buffer.
#include <VertexArray.h>
Public Member Functions
VertexBufferLayout ()
Default constructor initializing an empty layout.
template<typename T>
void Push (u32 count)
Templated method to add a vertex attribute to the layout.
const std::vector< VertexBufferElement > & GetElements () const
Gets the list of vertex buffer elements in the layout.
u32 GetStride () const
Gets the stride (total size) of the vertex structure in bytes.
template<>
void Push (u32 count)
Specialization for float (f32) vertex attributes.
template<>
void Push (u32 count)
Specialization for unsigned int (u32) vertex attributes.
template<>
void Push (u32 count)
Specialization for unsigned byte (u8) vertex attributes.
Private Attributes
std::vector< VertexBufferElement > m_Elements
The list of vertex buffer elements defining the layout.
u32 m_Stride
The total size of the vertex structure in bytes.
Detailed Description
Defines the layout of vertex attributes in a vertex buffer.
Manages a list of VertexBufferElement instances and calculates the stride (total size) of the vertex structure.
Definition at line 62 of file VertexArray.h.
Constructor & Destructor Documentation
VertexBufferLayout()
VertexBufferLayout::VertexBufferLayout () inline
Default constructor initializing an empty layout.
Definition at line 67 of file VertexArray.h.
References m_Stride.
Member Function Documentation
GetElements()
const std::vector< VertexBufferElement > & VertexBufferLayout::GetElements () const inline
Gets the list of vertex buffer elements in the layout.
Returns
const std::vector<VertexBufferElement>& The list of elements
Definition at line 87 of file VertexArray.h.
References m_Elements.
Referenced by VertexArray::AddVertexBuffer().
GetStride()
u32 VertexBufferLayout::GetStride () const inline
Gets the stride (total size) of the vertex structure in bytes.
Returns
u32 The stride in bytes
Definition at line 96 of file VertexArray.h.
References m_Stride.
Referenced by VertexArray::AddVertexBuffer().
Push() [1/4]
template<> void VertexBufferLayout::Push (u32 count) inline
Specialization for unsigned byte (u8) vertex attributes.
Parameters
count The number of unsigned byte components
Definition at line 140 of file VertexArray.h.
References VertexBufferElement::GetSizeOfType(), m_Elements, and m_Stride.
Push() [2/4]
template<> void VertexBufferLayout::Push (u32 count) inline
Specialization for unsigned int (u32) vertex attributes.
Parameters
count The number of unsigned int components
Definition at line 129 of file VertexArray.h.
References VertexBufferElement::GetSizeOfType(), m_Elements, and m_Stride.
Push() [3/4]
template<> void VertexBufferLayout::Push (u32 count) inline
Specialization for float (f32) vertex attributes.
Parameters
count The number of float components
Definition at line 118 of file VertexArray.h.
References VertexBufferElement::GetSizeOfType(), m_Elements, and m_Stride.
Push() [4/4]
template<typename T> void VertexBufferLayout::Push (u32 count) inline
Templated method to add a vertex attribute to the layout.
Specializations exist for f32, u32, and u8 types.
Template Parameters
T The data type of the vertex attribute
Parameters
count The number of components in the attribute
Definition at line 78 of file VertexArray.h.
Referenced by Mesh::Mesh().
Member Data Documentation
m_Elements
std::vector<VertexBufferElement> VertexBufferLayout::m_Elements private
The list of vertex buffer elements defining the layout.
Definition at line 103 of file VertexArray.h.
Referenced by GetElements(), and Push().
m_Stride
u32 VertexBufferLayout::m_Stride private
The total size of the vertex structure in bytes.
Definition at line 109 of file VertexArray.h.
Referenced by GetStride(), Push(), and VertexBufferLayout().
The documentation for this class was generated from the following file:
src/Graphics/VertexArray.h