MyGameEngine: VertexArray Class Reference
VertexArray Class Reference
Encapsulates an OpenGL vertex array object (VAO).
#include <VertexArray.h>
Public Member Functions
VertexArray ()
Constructs a new VertexArray and generates the OpenGL VAO.
~VertexArray ()
Destructor that cleans up the OpenGL VAO.
void Bind () const
Binds the vertex array for rendering.
void Unbind () const
Unbinds the vertex array.
void AddVertexBuffer (const Ref< VertexBuffer > &vertexBuffer, const VertexBufferLayout &layout)
Adds a vertex buffer to the vertex array with the specified layout.
void SetIndexBuffer (const Ref< IndexBuffer > &indexBuffer)
Sets the index buffer for the vertex array.
const std::vector< Ref< VertexBuffer > > & GetVertexBuffers () const
Gets the OpenGL renderer ID of the vertex array.
const Ref< IndexBuffer > & GetIndexBuffer () const
Gets the index buffer associated with the vertex array.
Private Attributes
u32 m_RendererID
The OpenGL renderer ID for the vertex array object.
u32 m_VertexBufferIndex = 0
The current index for vertex buffer attributes.
std::vector< Ref< VertexBuffer > > m_VertexBuffers
The list of vertex buffers associated with this vertex array.
Ref< IndexBuffer > m_IndexBuffer
The index buffer associated with this vertex array.
Detailed Description
Encapsulates an OpenGL vertex array object (VAO).
Manages the binding of vertex buffers and index buffers for rendering.
Definition at line 151 of file VertexArray.h.
Constructor & Destructor Documentation
VertexArray()
VertexArray::VertexArray ()
Constructs a new VertexArray and generates the OpenGL VAO.
Definition at line 5 of file VertexArray.cpp.
References m_RendererID.
~VertexArray()
VertexArray::~VertexArray ()
Destructor that cleans up the OpenGL VAO.
Definition at line 7 of file VertexArray.cpp.
References m_RendererID.
Member Function Documentation
AddVertexBuffer()
void VertexArray::AddVertexBuffer (const Ref< VertexBuffer > & vertexBuffer, const VertexBufferLayout & layout)
Adds a vertex buffer to the vertex array with the specified layout.
Configures the vertex attribute pointers based on the provided layout.
Parameters
vertexBuffer The vertex buffer to add
layout The layout describing the vertex attributes
Definition at line 13 of file VertexArray.cpp.
References Bind(), VertexBufferLayout::GetElements(), VertexBufferElement::GetSizeOfType(), VertexBufferLayout::GetStride(), m_VertexBufferIndex, and m_VertexBuffers.
Bind()
void VertexArray::Bind () const
Binds the vertex array for rendering.
Definition at line 9 of file VertexArray.cpp.
References m_RendererID.
Referenced by AddVertexBuffer(), and SetIndexBuffer().
GetIndexBuffer()
const Ref< IndexBuffer > & VertexArray::GetIndexBuffer () const inline
Gets the index buffer associated with the vertex array.
Returns
const Ref<IndexBuffer>& The index buffer
Definition at line 205 of file VertexArray.h.
References m_IndexBuffer.
GetVertexBuffers()
const std::vector< Ref< VertexBuffer > > & VertexArray::GetVertexBuffers () const inline
Gets the OpenGL renderer ID of the vertex array.
Returns
u32 The OpenGL renderer ID
Definition at line 196 of file VertexArray.h.
References m_VertexBuffers.
SetIndexBuffer()
void VertexArray::SetIndexBuffer (const Ref< IndexBuffer > & indexBuffer)
Sets the index buffer for the vertex array.
Parameters
indexBuffer The index buffer to set
Definition at line 34 of file VertexArray.cpp.
References Bind(), and m_IndexBuffer.
Unbind()
void VertexArray::Unbind () const
Unbinds the vertex array.
Definition at line 11 of file VertexArray.cpp.
Member Data Documentation
m_IndexBuffer
Ref<IndexBuffer> VertexArray::m_IndexBuffer private
The index buffer associated with this vertex array.
Definition at line 230 of file VertexArray.h.
Referenced by GetIndexBuffer(), and SetIndexBuffer().
m_RendererID
u32 VertexArray::m_RendererID private
The OpenGL renderer ID for the vertex array object.
Definition at line 212 of file VertexArray.h.
Referenced by Bind(), VertexArray(), and ~VertexArray().
m_VertexBufferIndex
u32 VertexArray::m_VertexBufferIndex = 0 private
The current index for vertex buffer attributes.
Definition at line 218 of file VertexArray.h.
Referenced by AddVertexBuffer().
m_VertexBuffers
std::vector<Ref<VertexBuffer> > VertexArray::m_VertexBuffers private
The list of vertex buffers associated with this vertex array.
Definition at line 224 of file VertexArray.h.
Referenced by AddVertexBuffer(), and GetVertexBuffers().
The documentation for this class was generated from the following files:
src/Graphics/VertexArray.h
src/Graphics/VertexArray.cpp