MyGameEngine: Engine Class Reference
Engine Class Reference abstract
Public Member Functions
Engine ()
Constructs a new Engine instance.
virtual ~Engine ()
Destroys the Engine instance and cleans up resources.
void Run ()
bool Initialize ()
void Shutdown ()
virtual void OnEvent (Event &event)=0
f32 GetDeltaTime () const
Gets the application window.
f32 GetFPS () const
Gets the current frames per second (FPS).
Static Public Member Functions
static Engine & Get ()
Gets the singleton instance of the Engine.
Protected Member Functions
virtual void OnInitialize ()
Called during engine initialization. Override this method in derived classes to implement game-specific initialization logic.
virtual void OnUpdate (f32 deltaTime)=0
Called each frame to update game logic. Override this method in derived classes to implement game-specific update logic.
virtual void OnRender ()
Called each frame to render the scene. Override this method in derived classes to implement game-specific rendering logic.
virtual void OnShutdown ()
Called during engine shutdown. Override this method in derived classes to implement game-specific cleanup logic.
Private Member Functions
void ProcessInput ()
Processes input events. This function polls and handles input events from the windowing system.
void Update (f32 deltaTime)
Updates the engine state. This function updates game logic and timing information.
void Render ()
Renders the current frame. This function calls the game-specific rendering logic.
Private Attributes
Scope< Window > m_Window_
Scoped pointer to the main application window.
Time::Timer m_Timer_
Timer instance for tracking elapsed time and delta time.
f32 m_DeltaTime_ = 0.0f
Time elapsed since the last frame in seconds.
f32 m_FPS_ = 0.0f
Current frames per second (FPS) value.
u32 m_FrameCount_ = 0
Number of frames rendered in the current second.
f32 m_FPSTimer_ = 0.0f
Accumulated time for FPS calculation.
bool m_isRunning_ = false
Flag indicating whether the main loop is running.
bool m_isMinimized = false
Flag indicating whether the window is minimized.
Static Private Attributes
static Engine * s_Instance_ = nullptr
Static pointer to the singleton Engine instance.
Detailed Description
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 58 of file Engine.h.
Constructor & Destructor Documentation
Engine()
Engine::Engine ()
Constructs a new Engine instance.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 7 of file Engine.cpp.
References s_Instance_.
Referenced by Get().
~Engine()
Engine::~Engine () virtual
Destroys the Engine instance and cleans up resources.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 16 of file Engine.cpp.
References s_Instance_.
Member Function Documentation
Get()
Engine & Engine::Get () inline static
Gets the singleton instance of the Engine.
Returns
Engine& Reference to the global Engine instance
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 129 of file Engine.h.
References Engine(), and s_Instance_.
GetDeltaTime()
f32 Engine::GetDeltaTime () const inline
Gets the application window.
Returns
Window& Reference to the engine's main window
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 134 of file Engine.h.
References m_DeltaTime_.
GetFPS()
f32 Engine::GetFPS () const inline
Gets the current frames per second (FPS).
Returns
f32 Current FPS value
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 139 of file Engine.h.
References m_FPS_.
Initialize()
bool Engine::Initialize ()
Definition at line 22 of file Engine.cpp.
OnInitialize()
virtual void Engine::OnInitialize () inline protected virtual
Called during engine initialization. Override this method in derived classes to implement game-specific initialization logic.
Reimplemented in TestApp.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 149 of file Engine.h.
OnRender()
virtual void Engine::OnRender () inline protected virtual
Called each frame to render the scene. Override this method in derived classes to implement game-specific rendering logic.
Reimplemented in TestApp.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 164 of file Engine.h.
Referenced by Render().
OnShutdown()
virtual void Engine::OnShutdown () inline protected virtual
Called during engine shutdown. Override this method in derived classes to implement game-specific cleanup logic.
Reimplemented in TestApp.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 171 of file Engine.h.
OnUpdate()
virtual void Engine::OnUpdate (f32 deltaTime) protected pure virtual
Called each frame to update game logic. Override this method in derived classes to implement game-specific update logic.
Parameters
deltaTime Time elapsed since the last frame in seconds
Implemented in TestApp.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Referenced by Update().
ProcessInput()
void Engine::ProcessInput () private
Processes input events. This function polls and handles input events from the windowing system.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 103 of file Engine.cpp.
References m_isRunning_.
Render()
void Engine::Render () private
Renders the current frame. This function calls the game-specific rendering logic.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 122 of file Engine.cpp.
References m_Window_, and OnRender().
Run()
void Engine::Run ()
Definition at line 58 of file Engine.cpp.
Shutdown()
void Engine::Shutdown ()
Definition at line 44 of file Engine.cpp.
Update()
void Engine::Update (f32 deltaTime) private
Updates the engine state. This function updates game logic and timing information.
Parameters
deltaTime Time elapsed since the last frame in seconds
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 118 of file Engine.cpp.
References OnUpdate().
Member Data Documentation
m_DeltaTime_
f32 Engine::m_DeltaTime_ = 0.0f private
Time elapsed since the last frame in seconds.
Used for frame-rate independent updates and timing calculations.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 228 of file Engine.h.
Referenced by GetDeltaTime().
m_FPS_
f32 Engine::m_FPS_ = 0.0f private
Current frames per second (FPS) value.
Updated each frame to reflect the current rendering performance.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 236 of file Engine.h.
Referenced by GetFPS().
m_FPSTimer_
f32 Engine::m_FPSTimer_ = 0.0f private
Accumulated time for FPS calculation.
Used to track elapsed time for updating the FPS value once per second.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 252 of file Engine.h.
m_FrameCount_
u32 Engine::m_FrameCount_ = 0 private
Number of frames rendered in the current second.
Used to calculate the FPS value.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 244 of file Engine.h.
m_isMinimized
bool Engine::m_isMinimized = false private
Flag indicating whether the window is minimized.
Used to pause updates and rendering when the window is not visible.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 268 of file Engine.h.
m_isRunning_
bool Engine::m_isRunning_ = false private
Flag indicating whether the main loop is running.
Used to control the execution of the main application loop.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 260 of file Engine.h.
Referenced by ProcessInput().
m_Timer_
Time::Timer Engine::m_Timer_ private
Timer instance for tracking elapsed time and delta time.
Used to measure frame times and provide timing information to the engine.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 220 of file Engine.h.
m_Window_
Scope<Window> Engine::m_Window_ private
Scoped pointer to the main application window.
Manages the lifecycle of the window used for rendering and input.
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 212 of file Engine.h.
Referenced by Render().
s_Instance_
Engine * Engine::s_Instance_ = nullptr static private
Static pointer to the singleton Engine instance.
Used to provide global access to the Engine instance via Engine::Get().
Examples
C:/Users/PC/source/repos/engine/src/Core/Engine.h.
Definition at line 204 of file Engine.h.
Referenced by Engine(), Get(), and ~Engine().
The documentation for this class was generated from the following files:
src/Core/Engine.h
src/Core/Engine.cpp